language: python
python: '3.6'
install: pip install virtualenv
script: make
after_success: make push
branches:
    except:
        - gh-pages
env:
    global:
        # GH_TOKEN
        - secure: "UxjGGBAKCDChn4Iirizr7TiZ1ENkSTuZ83lfYKwYanU1c4T9Hon+Z3b+x6UzIPra+yqHinlLWw/s9UP4pqhiiBYwlXITsdsc67I9LfLH7ZfFsBbSaSJtK523zxxYeycmG9tLsUCwz+PFf+Ru38SYVitmwyNu3w6KUu7UPBJ6MoaR1yEZhxIVuanxSZ6/TlLcpfX52W7vV8hrSVDWmqvbFUpR5BTysGeRfGQv5z7YPVM3JTJN1sVWlMS7Z0mq0hxFSrcUFEBgRn3GWpLHvSvck4+csvyXhfyEQUjDTP7vnNAvMQDlTkCuxxfi5CQ5hFuR85XZYf5trT9qwSeeXNCxV/X3SZf+iO2M+ERWmnUJframmmEInr5MBGfmj+clkAcaNuitP/42FlGZpdJMNCk7aJWzIbj6GeRAVzoJugHQiKCDl8kNlAbPa0ARp7+dAcHZ0KU0HW4hevTrD6zZl9+tGWLlDHsDuJ9bloANwmXF0Ly4ZJg5g7eg4v4yq0Vktv6JxMCK+/Uxy5sHNCI1hi97r3FgoPsvjYwCTNqRu1J3pNk5z8ywsmBxk0MPVrV/fx/6lZ/2Txlft3S2VzF3lgvQSGuACdfkwww1XTWKXUDCPCqrGSI2qZ1EYq8zdZ5hXknhgVawgqhSlV/rZ39cB6S18jFLr2I+6YH2Uhf9VDderlk="
cache:
    directories:
        - "$HOME/.cache/pip"
        - "$HOME/.cache/pre-commit"
