language: python
python: '3.6'
install: pip install virtualenv
script: make
after_success: ./push-to-gh.sh
branches:
    except:
        - gh-pages
env:
    global:
        # GH_TOKEN
        - secure: "hqNCk7+3pZxxMHF8sr49zB8rP8oxvv6iLi4/BBm+OQwoWoram0yn+gTAi5q35lewLk6nz/w68tCpown1UmeSFkAulvRMZstq/dC5pQ8FDwK0gtfRrhX7+gTFOV/+3yrxAllyi4eKzF3GebOizoVSLG1+dsuQs43VIV7wguJSM0r/LmbwaFf8eAFPVMm8hKR8R8mglw0Q2b4h0H3EWUjOaEtzQAWX/VbIe48Qat/64ybjmTX1TWGefMIqiDRJvHj8ITXu/kkNLnhXFGZ7ShnghYI7LJp+VlMmCLRd0xjpri6SGHvtKNVm7Zdnh30o1Fr49CbynwYoO/ZckAC49vmdkoT5dPkU6UdMcx46EiLlP9JOVhIUEpqh6OZ2GNodGox0az/aEBVkw/BQ0ZuRJR6MT0TegvYF9j1IkgfqhjU3XwOjFYcPMLdqeRwvl4xrlnIrWzY5pTCzAL1Dg6qs2wS0xxYQ5k+f+ApA9yhwHRGmmlRDBIpaP7S4GbimpeDjgpIzp0r+fwRQB7tDSpBrOq5V+hVTfEh6fzh6mv2v1PbOkHvuPUUmMUQy5f1gWhiZUFPIiwhii/A+jcvxswYIxruEhrPtJ+Fj3+bd9qitpwpqDXVFwY3RRD/+gdcIX4+1oaHkSTfSesbIFJtg3b6/vQVL8GtkdaiDoR288vKbuoPY4EI="
cache:
    directories:
        - "$HOME/.cache/pip"
        - "$HOME/.pre-commit"
